    - name: Init master node
      ansible.builtin.shell: "kubeadm init --pod-network-cidr={{ network_cidr }} --apiserver-advertise-address={{ private_ip }} --service-cidr={{ network_cidr }}"
      become: yes
      register: init_output

    - name: Debug master node
      ansible.builtin.debug:
        var: init_output

    - name: Setup environment on the master node
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Check status at the master node
      ansible.builtin.shell: "kubectl get node"

    - name: Copy Flannel yaml
      ansible.builtin.copy:
        src: kube-flannel.yml
        dest: ~/kube-flannel.yml
        mode: '0644'

    - name: Apply Flannel
      ansible.builtin.shell: "kubectl apply -f ~/kube-flannel.yml"
