    - name: Initialize the cluster
      ansible.builtin.shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ private_ip }}"
      become: yes
      register: init_output

    - name: Debug master node
      ansible.builtin.debug:
        var: init_output

    - name: Setup vagrant user
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Setup root user
      ansible.builtin.shell: |
        whoami
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      become: yes

    - name: Check status at the master node
      ansible.builtin.shell: "kubectl get node"

    - name: Copy Flannel yaml
      ansible.builtin.copy:
        src: kube-flannel.yml
        dest: ~/kube-flannel.yml
        mode: '0644'

    - name: Apply Flannel
      ansible.builtin.shell: "kubectl apply -f ~/kube-flannel.yml"
