apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 172.16.20.12
    ports:
      - port: 1
  - addresses:
      - ip: 172.16.20.13
    ports:
      - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: default
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume01
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume01"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume02
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume02"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume03
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume03"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume04
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume04"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume05
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume05"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume06
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume06"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume07
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume07"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume08
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume08"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume09
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume09"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume10
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "volume10"
    readOnly: false
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: glusterfs-nginx
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi