---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: default
spec:
  selector:
    app: kafdrop
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 32001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      name: kafdrop
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop
        imagePullPolicy: IfNotPresent
        ports:
        - name: kafdrop
          containerPort: 9000
        resources:
          limits:
            memory: "0.3G"
            cpu: "0.3"
          requests:
            memory: "0.1G"
            cpu: "0.1"
        env:
        - name: KAFKA_BROKERCONNECT
          value : "kafka-hs.default.svc.cluster.local"
        - name: JVM_OPTS
          value: "-Xms32M -Xmx64M"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"
---
