apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |-
      global:
        scrape_interval: 10s
        evaluation_interval: 10s
      scrape_configs:
      - job_name: 'kminion'
        static_configs:
          - targets:
            - kminion-hs.default.svc.cluster.local:8080
      - job_name: 'kafka-consumer'
        static_configs:
          - targets:
            - kafka-consumer-hs.default.svc.cluster.local:8001
      - job_name: 'kafka-producer'
        static_configs:
          - targets:
            - kafka-producer-hs.default.svc.cluster.local:8002
      # - job_name: 'jmx-kafka-exporter'
      #   static_configs:
      #     - targets:
      #       - kminion.default.svc.cluster.local:8080
