---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node
  namespace: default
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - port: 9090
    nodePort: 32090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-hs
  namespace: default
spec:
  clusterIP: None
  selector:
    app: prometheus
  ports:
  - port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - name: prometheus
          containerPort: 9090
        resources:
          limits:
            memory: "400M"
            cpu: "0.4"
          requests:
            memory: "100M"
            cpu: "0.1"
        # command:
        # - sh prometheus --config.file=/etc/prometheus/prometheus-config.yml
        env:
        - name: KAFKA_BROKERCONNECT
          value : "kafka-hs.default.svc.cluster.local"
        - name: JVM_OPTS
          value: "-Xms32M -Xmx64M"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"
        volumeMounts:
        - name: prometheus-etc
          mountPath: /etc/prometheus
      volumes:
        - name: prometheus-etc
          configMap:
            name: prometheus-config
---
