---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-hs
  namespace: default
spec:
  selector:
    app: kafka-producer
  clusterIP: None
  ports:
  - port: 8001
    name: exporter
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: default
  labels:
    app: kafka-producer
spec:
  containers:
  - name: kafka-producer
    image: docker.io/urpylka/kafka-producer:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8001
      name: exporter
    resources:
      requests:
        memory: "100M"
        cpu: "50m"
  restartPolicy: Always
---
