---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-hs
  labels:
    app: kafka-consumer
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 8002
    name: exporter
  selector:
    app: kafka-consumer
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
  namespace: default
spec:
  containers:
  - name: kafka-consumer
    image: docker.io/urpylka/kafka-consumer:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8002
      name: exporter
    resources:
      limits:
        memory: "100M"
        cpu: "50m"
      requests:
        memory: "50M"
        cpu: "25m"
  restartPolicy: Always
---
