---
- hosts: all

  tasks:

    - name: Install software
      include_role:
        name: install_k8s

    - name: Create target directory
      ansible.builtin.file: path=/etc/systemd/system/kubelet.service.d state=directory mode=0755
      become: yes

    # - name: Add k8s config
    #   ansible.builtin.template:
    #     src: 10-kubeadm.conf
    #     dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    #   become: yes

    - name: Restart kubelet service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
      become: yes

    - name: Check kubelet service
      ansible.builtin.systemd:
        state: started
        name: kubelet

    - name: Setup master node
      include_role:
        name: setup_master
      when: vm_name == "master"
