---
- hosts: all

  tasks:

    - name: Install software
      include_role:
        name: install_k8s

    - name: Install glusterfs
      include_role:
        name: install_gluster

    - name: Setup master node
      include_role:
        name: setup_master
      when: vm_name == "master"

    - name: Setup common node
      include_role:
        name: setup_node
      when: vm_name != "master"

    - name: Copy files to master
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /k8s/
      with_fileglob:
        - k8s/*
      when: vm_name == "master"
      become: yes

    - name: Enable solution
      ansible.builtin.shell: |
        chmod +x /k8s/wait.sh
        nohup /k8s/wait.sh > /k8s/setup.log &
      when: vm_name == "master"
      become: yes
