---
- hosts: all

  tasks:

    - name: Install software
      include_role:
        name: install_k8s

    - name: Restart kubelet service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
      become: yes

    - name: Check kubelet service
      ansible.builtin.systemd:
        state: started
        name: kubelet

    - name: Setup master node
      include_role:
        name: setup_master
      when: vm_name == "master"

    - name: Setup common node
      include_role:
        name: setup_node
      when: vm_name != "master"
