---
- hosts: all

  tasks:

    - name: Install software
      include_role:
        name: install_k8s

    - name: Install glusterfs
      include_role:
        name: install_gluster

    - name: Setup gluster
      include_role:
        name: setup_gluster
      when: vm_name == "master"

    - name: Setup master node
      include_role:
        name: setup_master
      when: vm_name == "master"

    - name: Setup common node
      include_role:
        name: setup_node
      when: vm_name != "master"

    - name: Enable solution
      ansible.builtin.shell: |
        kubectl apply -k /vagrant/k8s/mykafka
      when: vm_name == "master"
